TYPE=VIEW
query=select `u`.`name` AS `name`,`u`.`phone` AS `phone`,`u`.`address` AS `address`,`x`.`g_name` AS `g_name`,`g`.`g_icon` AS `g_icon`,`g`.`g_type` AS `g_type`,`x`.`uid` AS `uid`,`x`.`gid` AS `gid`,`x`.`total` AS `total`,`y`.`non` AS `non` from (((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`)) `x` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `y` on(`x`.`gid` = `y`.`gid` and `x`.`uid` = `y`.`uid` and `x`.`g_name` = `y`.`g_name`)) join `spin`.`users` `u` on(`x`.`uid` = `u`.`uid`)) join `spin`.`gifts` `g` on(`g`.`gid` = `x`.`gid`))
md5=83036403e65f06b3dd175cddf78cc7f4
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2020-10-17 07:56:17
create-version=2
source=select `U`.`name` AS `name`,`U`.`phone` AS `phone`,`U`.`address` AS `address`,`X`.`g_name` AS `g_name`,`G`.`g_icon` AS `g_icon`,`G`.`g_type` AS `g_type`,`X`.`uid` AS `uid`,`X`.`gid` AS `gid`,`X`.`total` AS `total`,`Y`.`non` AS `non` from ((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `X` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `Y` on(`X`.`gid` = `Y`.`gid` and `X`.`uid` = `Y`.`uid` and `X`.`g_name` = `Y`.`g_name`)) join `spin`.`users` `U` on(`X`.`uid` = `U`.`uid`)) join `spin`.`gifts` `G` on(`G`.`gid` = `X`.`gid`))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `u`.`name` AS `name`,`u`.`phone` AS `phone`,`u`.`address` AS `address`,`x`.`g_name` AS `g_name`,`g`.`g_icon` AS `g_icon`,`g`.`g_type` AS `g_type`,`x`.`uid` AS `uid`,`x`.`gid` AS `gid`,`x`.`total` AS `total`,`y`.`non` AS `non` from (((((select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `total` from `spin`.`user_gifts` group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`)) `x` left join (select `spin`.`user_gifts`.`uid` AS `uid`,`spin`.`user_gifts`.`gid` AS `gid`,`spin`.`user_gifts`.`g_name` AS `g_name`,count(`spin`.`user_gifts`.`id`) AS `non` from `spin`.`user_gifts` where `spin`.`user_gifts`.`status` = 0 group by `spin`.`user_gifts`.`gid`,`spin`.`user_gifts`.`uid`,`spin`.`user_gifts`.`g_name`) `y` on(`x`.`gid` = `y`.`gid` and `x`.`uid` = `y`.`uid` and `x`.`g_name` = `y`.`g_name`)) join `spin`.`users` `u` on(`x`.`uid` = `u`.`uid`)) join `spin`.`gifts` `g` on(`g`.`gid` = `x`.`gid`))
mariadb-version=100234
